#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-site-plugin
Version  : 3.5.1
Release  : 1
URL      : https://github.com/apache/maven-site-plugin/archive/maven-site-plugin-3.5.1.tar.gz
Source0  : https://github.com/apache/maven-site-plugin/archive/maven-site-plugin-3.5.1.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.5.1/maven-site-plugin-3.5.1.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.5.1/maven-site-plugin-3.5.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
The projects under parentNotAsRef/ and parentAsRef/ are identical
except for the inheritAsRef parameter in the parent's site.xml.

%prep

%build

%install

%files
%defattr(-,root,root,-)
